### ISSUE TITLE
Pending avatars with missing WCA ID prevent actions on all avatars

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#1117]
If a user submit an avatar, and its WCA ID is removed before the avatar submission has been handled, it generates an CSRF authenticity token error when trying to update any avatar.

>I, [2017-01-19T09:46:39.602684 #3327]  INFO -- : Completed 422 Unprocessable Entity in 0ms (ActiveRecord: 0.0ms)
I, [2017-01-19T09:46:39.602847 #3327]  INFO -- : [User Id] Request was made by user id: 277
F, [2017-01-19T09:46:39.603987 #3327] FATAL -- : 
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
  lib/middlewares/warden_user_logger.rb:12:in `call'
  lib/middlewares/fix_accept_header.rb:13:in `call'

(It's reproducible locally)

**Comment by dunkOnIT** [comment]
@gregorbg assuming this is fixed
