### ISSUE TITLE
Crash in _associated_events_picker

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1563]
`def create` in `WcaOnRails/app/controllers/registrations_controller.rb` does not define `@selected_events`, which is passed down into _associated_events_picker:

```
I, [2017-04-25T18:03:23.414865 #5360]  INFO -- : [7e866a51-dc6e-4647-a331-a3e6293d07d1] Completed 500 Internal Server Error in 89ms (ActiveRecord: 26.4ms)
I, [2017-04-25T18:03:23.415059 #5360]  INFO -- : [7e866a51-dc6e-4647-a331-a3e6293d07d1] [User Id] Request was made by user id: 55426
F, [2017-04-25T18:03:23.416807 #5360] FATAL -- : [7e866a51-dc6e-4647-a331-a3e6293d07d1]
F, [2017-04-25T18:03:23.416871 #5360] FATAL -- : [7e866a51-dc6e-4647-a331-a3e6293d07d1] ActionView::Template::Error (undefined method `include?' for nil:NilClass):
F, [2017-04-25T18:03:23.416998 #5360] FATAL -- : [7e866a51-dc6e-4647-a331-a3e6293d07d1]     37:           <%= f.hidden_field :event_id %>
[7e866a51-dc6e-4647-a331-a3e6293d07d1]     38:         <% end %>
[7e866a51-dc6e-4647-a331-a3e6293d07d1]     39:         <%= label_tag "#{events_association_name}_#{event.id}" do %>
[7e866a51-dc6e-4647-a331-a3e6293d07d1]     40:           <%= f.check_box "_destroy", { checked: selected_events.include?(event), id: "#{events_association_name}_#{event.id}", disabled: disabled }, "0", "1" %>
[7e866a51-dc6e-4647-a331-a3e6293d07d1]     41:           <%= content_tag(:span, "",
[7e866a51-dc6e-4647-a331-a3e6293d07d1]     42:                           class: "cubing-icon event-#{event.id}",
[7e866a51-dc6e-4647-a331-a3e6293d07d1]     43:                           data: { toggle: "tooltip", placement: "top" },
F, [2017-04-25T18:03:23.417025 #5360] FATAL -- : [7e866a51-dc6e-4647-a331-a3e6293d07d1]
F, [2017-04-25T18:03:23.417050 #5360] FATAL -- : [7e866a51-dc6e-4647-a331-a3e6293d07d1] app/views/shared/_associated_events_picker.html.erb:40:in `block (2 levels) in _app_views_shared__associated_events_picker_html_erb__998595799881894562_146239620'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] app/views/shared/_associated_events_picker.html.erb:39:in `block in _app_views_shared__associated_events_picker_html_erb__998595799881894562_146239620'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] app/views/shared/_associated_events_picker.html.erb:31:in `_app_views_shared__associated_events_picker_html_erb__998595799881894562_146239620'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] app/views/registrations/_register_form.html.erb:5:in `block in _app_views_registrations__register_form_html_erb___1835458308549085378_136920160'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] app/helpers/application_helper.rb:154:in `block in simple_form_for'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] app/helpers/application_helper.rb:153:in `simple_form_for'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] app/helpers/application_helper.rb:171:in `horizontal_simple_form_for'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] app/views/registrations/_register_form.html.erb:4:in `_app_views_registrations__register_form_html_erb___1835458308549085378_136920160'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] app/views/registrations/register.html.erb:111:in `block in _app_views_registrations_register_html_erb__3099440248651085455_116317160'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] app/views/registrations/_nav.html.erb:2:in `block in _app_views_registrations__nav_html_erb___3461379694517932504_121217120'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] app/views/competitions/_nav.html.erb:194:in `_app_views_competitions__nav_html_erb__3712584462947809348_110030020'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] app/views/registrations/_nav.html.erb:1:in `_app_views_registrations__nav_html_erb___3461379694517932504_121217120'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] app/views/registrations/register.html.erb:3:in `_app_views_registrations_register_html_erb__3099440248651085455_116317160'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] app/controllers/registrations_controller.rb:288:in `create'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] lib/middlewares/warden_user_logger.rb:13:in `call'
[7e866a51-dc6e-4647-a331-a3e6293d07d1] lib/middlewares/fix_accept_header.rb:14:in `call'
```

What I don't understand is how this works for anyone. Or does everyone just see the resulting 500 page and ignore it, because their registration actually gets created?

**Comment by viroulep** [comment]
We discussed this offline, but this occurs when submitting an invalid registration (empty events, negative guests,...): valid registrations redirect, invalid render with a missing `@selected_events` :s
