### ISSUE TITLE
ActionView::Template::Error (uninitialized constant ActionView::CompiledTemplates::DatabaseDumper) in production

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1702]
This is due to [this reference to `DatabaseDumper`](https://github.com/thewca/worldcubeassociation.org/blob/1f6b74f4edb909e39d1f93cc3da9de5d739fd9fd/WcaOnRails/app/views/devise/sessions/new.html.erb#L19). The problem seems to be that the contents of the `lib` directory are not eagerly loaded in production. Here's a very interesting article about rails's autoloading vs eager loading: http://blog.arkency.com/2014/11/dont-forget-about-eager-load-when-extending-autoload/.

<details>

```
I, [2017-06-01T22:28:50.526851 #21905]  INFO -- : [bc6f8d20-9006-47c8-85d3-680895144f7d] Started GET "/users/sign_in" for 54.182.170.51 at 2017-06-01 22:28:50 +0000
I, [2017-06-01T22:28:50.528168 #21905]  INFO -- : [bc6f8d20-9006-47c8-85d3-680895144f7d] Processing by Devise::SessionsController#new as HTML
I, [2017-06-01T22:28:50.529862 #21905]  INFO -- : [bc6f8d20-9006-47c8-85d3-680895144f7d]   Rendering devise/sessions/new.html.erb within layouts/application
I, [2017-06-01T22:28:50.532495 #21905]  INFO -- : [bc6f8d20-9006-47c8-85d3-680895144f7d]   Rendered devise/_conversion_message.html.erb (2.3ms)
I, [2017-06-01T22:28:50.532592 #21905]  INFO -- : [bc6f8d20-9006-47c8-85d3-680895144f7d]   Rendered devise/sessions/new.html.erb within layouts/application (2.7ms)
I, [2017-06-01T22:28:50.532718 #21905]  INFO -- : [bc6f8d20-9006-47c8-85d3-680895144f7d] Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms)
I, [2017-06-01T22:28:50.532879 #21905]  INFO -- : [bc6f8d20-9006-47c8-85d3-680895144f7d] [User Id] Request was made by user id: <not logged in>
F, [2017-06-01T22:28:50.534221 #21905] FATAL -- : [bc6f8d20-9006-47c8-85d3-680895144f7d]
F, [2017-06-01T22:28:50.534255 #21905] FATAL -- : [bc6f8d20-9006-47c8-85d3-680895144f7d] ActionView::Template::Error (uninitialized constant ActionView::CompiledTemplates::DatabaseDumper):
F, [2017-06-01T22:28:50.534333 #21905] FATAL -- : [bc6f8d20-9006-47c8-85d3-680895144f7d]     16: <% end %>
[bc6f8d20-9006-47c8-85d3-680895144f7d]     17:
[bc6f8d20-9006-47c8-85d3-680895144f7d]     18: <% if !conversion_shown %>
[bc6f8d20-9006-47c8-85d3-680895144f7d]     19:   <%= yield %>
[bc6f8d20-9006-47c8-85d3-680895144f7d]     20: <% end %>
F, [2017-06-01T22:28:50.534355 #21905] FATAL -- : [bc6f8d20-9006-47c8-85d3-680895144f7d]
F, [2017-06-01T22:28:50.534373 #21905] FATAL -- : [bc6f8d20-9006-47c8-85d3-680895144f7d] app/views/devise/sessions/new.html.erb:19:in `block (2 levels) in _app_views_devise_sessions_new_html_erb___2858679153006344524_94343180'
[bc6f8d20-9006-47c8-85d3-680895144f7d] app/views/devise/sessions/new.html.erb:10:in `block in _app_views_devise_sessions_new_html_erb___2858679153006344524_94343180'
[bc6f8d20-9006-47c8-85d3-680895144f7d] app/views/devise/_conversion_message.html.erb:19:in `_app_views_devise__conversion_message_html_erb___1312107117197458349_94288860'
[bc6f8d20-9006-47c8-85d3-680895144f7d] app/views/devise/sessions/new.html.erb:4:in `_app_views_devise_sessions_new_html_erb___2858679153006344524_94343180'
[bc6f8d20-9006-47c8-85d3-680895144f7d] lib/middlewares/warden_user_logger.rb:13:in `call'
[bc6f8d20-9006-47c8-85d3-680895144f7d] lib/middlewares/fix_accept_header.rb:14:in `call'
```

</details>

**Comment by jfly** [comment]
I'm going to optimistically declare this fixed by the work in PR #2022.
