### ISSUE TITLE
expect Post.count to eq 1 failure in spec/requests/competitions_spec.rb

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1807]
This is easily  reproduced with seed, but I don't think the seed is actually needed.

```
> bin/rspec -s 112 spec/requests/competitions_spec.rb
...
Failures:

  1) competitions can post results for a competition
     Failure/Error: expect(Post.count).to eq 1
     
       expected: 1
            got: 0
     
       (compared using ==)
     # ./spec/requests/competitions_spec.rb:110:in `block (2 levels) in <top (required)>'
     # /home/jeremy/.bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
     # /home/jeremy/.bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
     # /home/jeremy/.bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
     # /home/jeremy/.bundle/ruby/2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
     # /home/jeremy/.bundle/ruby/2.4.0/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
     # -e:1:in `<main>'

Finished in 3 minutes 50.5 seconds (files took 1.56 seconds to load)
1116 examples, 1 failure

Failed examples:

rspec ./spec/requests/competitions_spec.rb:105 # competitions can post results for a competition

Randomized with seed 112
```

**Comment by jfly** [comment]
Urg nevermind, see https://github.com/thewca/worldcubeassociation.org/pull/1808#issue-248284927.
