### ISSUE TITLE
`bin/rake db:load:development` fails in a not immediately obvious way if `unzip` is not installed

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1937]
Normally I'd say this is fine as is, but this is people's first introduction when working on our codebase, I think it's worth putting in a little extra effort here.

**Comment by jfly** [comment]
An except of what you see when unzip does not exist. At the very least, we should halt execution when the unzip command fails, rather than blindly trudging forward:

```
...
2017-09-17 12:20:15 (893 KB/s) - ‘wca-developer-database-dump.zip’ saved [142024155/142024155]

done in 155.72s
Unzipping wca-developer-database-dump.zip...rake: No such file or directory - unzip
done in 0.08s
Clobbering contents of 'wca_development' with wca-developer-database-dump.sql...done in 1.70s
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'wca_development.users' doesn't exist: SHOW FULL FIELDS FROM `users`
/home/jeremy/.bundle/ruby/2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `_query'
/home/jeremy/.bundle/ruby/2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `block in query'
/home/jeremy/.bundle/ruby/2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:119:in `handle_interrupt'
/home/jeremy/.bundle/ruby/2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:119:in `query'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
/home/jeremy/.bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/home/jeremy/.bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/home/jeremy/.bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:213:in `block in execute'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/home/jeremy/.bundle/ruby/2.4.0/gems/activesupport-5.1.3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:212:in `execute'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/mysql/database_statements.rb:26:in `execute'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:223:in `execute_and_free'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:854:in `column_definitions'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/abstract_adapter.rb:166:in `columns'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/schema_cache.rb:67:in `columns'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/connection_adapters/schema_cache.rb:73:in `columns_hash'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/model_schema.rb:471:in `load_schema!'
/home/jeremy/.bundle/ruby/2.4.0/gems/activerecord-5.1.3/lib/active_record/attributes.rb:233:in `load_schema!'
...
```
