### ISSUE TITLE
Random compilation failures in travis

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#3476]
Sometimes travis randomly fails at compiling our assets (see [here](https://travis-ci.org/thewca/worldcubeassociation.org/builds/442268381)).

The error is roughly:
```
ERROR in ./app/javascript/wca/events.js.erb
Module build failed: Error: rails-erb-loader failed with code: 1
    at ChildProcess.<anonymous> (/home/travis/build/thewca/worldcubeassociation.org/WcaOnRails/node_modules/rails-erb-loader/index.js:125:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
 @ ./app/javascript/edit-events/index.jsx 4:0-39
 @ ./app/javascript/packs/edit_events.js
```

Turns out it seems `rails-erb-loader` has an issue for this: https://github.com/usabilityhub/rails-erb-loader/issues/63.

Might be worth trying [to disable the spring preloader](https://github.com/usabilityhub/rails-erb-loader/issues/63#issuecomment-374791504), if we don't see any such failures in like a week we could conclude it works.

I didn't add this to #897, because it's clearly not *our* tests, and the source of the issue is known.

**Comment by viroulep** [comment]
Yes, since it worked for OP I'd just suggest to try this first.
Worst case it will happen again and we'll know it wasn't the issue :p

**Comment by jfly** [comment]
Wow, that is so awesome, thanks @viroulep!! This will definitely make our lives much better.
