### ISSUE TITLE
Stripe charge error set to NULL during timeouts

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#4305]
Stripe had an API outage a few days ago. From https://status.stripe.com/:

<img width="470" alt="2019-07-13_14-28-11_dalinar" src="https://user-images.githubusercontent.com/277474/61176769-ab98f780-a57b-11e9-826d-234d66fddc54.png">

This resulted in a few stripe charges in our `stripe_charges` database table with `status="unknown"`. One of them had a pretty straightforward 503 error from stripe:

<details>

```
mysql> select error from stripe_charges where id = 17793\G
error: #<Stripe::APIError: (Status 503) There was an unexpected error processing this request–we've been notified of this issue. We'll update our status page at https://status.stripe.com/ with more information if we're seeing systemic issues.>
/home/cubing/.bundle/ruby/2.5.0/gems/stripe-4.21.2/lib/stripe/stripe_client.rb:350:in `handle_error_response'
/home/cubing/.bundle/ruby/2.5.0/gems/stripe-4.21.2/lib/stripe/stripe_client.rb:301:in `rescue in execute_request_with_rescues'
/home/cubing/.bundle/ruby/2.5.0/gems/stripe-4.21.2/lib/stripe/stripe_client.rb:263:in `execute_request_with_rescues'
/home/cubing/.bundle/ruby/2.5.0/gems/stripe-4.21.2/lib/stripe/stripe_client.rb:184:in `execute_request'
/home/cubing/.bundle/ruby/2.5.0/gems/stripe-4.21.2/lib/stripe/api_operations/request.rb:19:in `request'
/home/cubing/.bundle/ruby/2.5.0/gems/stripe-4.21.2/lib/stripe/api_operations/create.rb:7:in `create'
/home/cubing/worldcubeassociation.org/WcaOnRails/app/controllers/registrations_controller.rb:403:in `journaled_stripe_charge'
/home/cubing/worldcubeassociation.org/WcaOnRails/app/controllers/registrations_controller.rb:362:in `process_payment'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/home/cubing/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:132:in `run_callbacks'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/home/cubing/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
/home/cubing/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/cubing/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/home/cubing/.bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'
/home/cubing/.bundle/ruby/2.5.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:32:in `process'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb:14:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/worldcubeassociation.org/WcaOnRails/lib/middlewares/warden_user_logger.rb:13:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/worldcubeassociation.org/WcaOnRails/lib/middlewares/fix_accept_header.rb:14:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
/home/cubing/.bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
/home/cubing/.bundle/ruby/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
/home/cubing/.bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/home/cubing/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'
/home/cubing/.bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
/home/cubing/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/home/cubing/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/cubing/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
/home/cubing/.bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/rack-cors-1.0.3/lib/rack/cors.rb:95:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
/home/cubing/.bundle/ruby/2.5.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:605:in `process_client'
/home/cubing/.bundle/ruby/2.5.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:700:in `worker_loop'
/home/cubing/.bundle/ruby/2.5.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:548:in `spawn_missing_workers'
/home/cubing/.bundle/ruby/2.5.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:562:in `maintain_worker_count'
/home/cubing/.bundle/ruby/2.5.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:295:in `join'
/home/cubing/.bundle/ruby/2.5.0/gems/unicorn-5.5.1/bin/unicorn:128:in `<top (required)>'
/home/cubing/.bundle/ruby/2.5.0/bin/unicorn:23:in `load'
/home/cubing/.bundle/ruby/2.5.0/bin/unicorn:23:in `<main>'
1 row in set (0.00 sec)
```

</details>

The other two had `error` set to NULL, though, which should never happen (note how [`journaled_stripe_charge` catches all exceptions and sets the `error` column](https://github.com/jfly/worldcubeassociation.org/blob/fd5a534f7b118cb192225d911aae4fcd98122969/WcaOnRails/app/controllers/registrations_controller.rb#L414-L421).

I dug into the logs around the time of these two stripe charges. Here's a snippet of our rails logs around the time of the failed request:

```
D, [2019-07-10T16:47:55.808011 #10825] DEBUG -- : [4a464996-3c07-4d00-a99f-8062ca51e6f6]   ^[[1m^[[36mStripeCharge Create (2.0ms)^[[0m  ^[[1m^[[32mINSERT INTO `stripe_charges` (`metadata`, `status`, `created_at`, `updated_at`) VALUES (REDACTED, ..., 'unknown', '2019-07-10 16:47:55', '2019-07-10 16:47:55')^[[0m
D, [2019-07-10T16:47:55.813042 #10825] DEBUG -- : [4a464996-3c07-4d00-a99f-8062ca51e6f6]   ^[[1m^[[35m (4.6ms)^[[0m  ^[[1m^[[35mCOMMIT^[[0m
```

This corresponds to [this line of code](https://github.com/jfly/worldcubeassociation.org/blob/fd5a534f7b118cb192225d911aae4fcd98122969/WcaOnRails/app/controllers/registrations_controller.rb#L396-L400) in `journaled_stripe_charge`. This is the last message we see from worker `10825`. Over in `/home/cubing/worldcubeassociation.org/WcaOnRails/log/unicorn-production.log`, I see the working timing out and getting killed:

```
E, [2019-07-10T16:48:26.952188 #32201] ERROR -- : worker=2 PID:10825 timeout (31s > 30s), killing
E, [2019-07-10T16:48:26.968171 #32201] ERROR -- : reaped #<Process::Status: pid 10825 SIGKILL (signal 9)> worker=2
```

I suspect that the worker went to start talking to Stripe, and was still waiting for a response when unicorn `SIGKILL`-ed it. This is why we never got a chance to set `status`.

We should probably configure our stripe client to not wait more than 30 seconds for a response from stripe. There's some information about how to do this here: https://github.com/stripe/stripe-ruby#configuring-timeouts. It looks like we currently have these settings:

```
^P~/worldcubeassociation.org/WcaOnRails @production> RACK_ENV=production bin/rails c
Loading production environment (Rails 5.2.3)
irb(main):001:0> Stripe.open_timeout
=> 30
irb(main):002:0> Stripe.read_timeout
=> 80
```

~I think this means we could end up waiting up to 80+30 = 110 seconds for an API call to stripe to go through. It would probably make sense to reconfigure this so that we cannot wait more than 30 seconds (we'd also want some buffer on top of that, so maybe no more than 20 seconds?).~ From reading the stripe source code, it looks like the `read_timeout` may actually be an open+read timeout? This get's a little complicated, see:
  - https://github.com/stripe/stripe-ruby/blob/5b5b0f5722d89e94c0b0b34bd2b6c475347ddb79/lib/stripe/stripe_client.rb#L186-L188 
  - https://github.com/lostisland/faraday/blob/bd322bba6b522e2ad28cad585f3c7227b5e2e2a6/lib/faraday/options/env.rb#L18
  - https://github.com/lostisland/faraday/blob/c8cf1ac53582d12bab82b8ea68c1ae816098ebc9/lib/faraday/adapter/excon.rb#L92-L104
  - https://github.com/excon/excon/blob/ca4f76a0323f1b52a9404ece5fe57421ffa8f7e4/lib/excon/socket.rb#L285-L293
  - https://ruby-doc.org/core-2.6.3/IO.html#method-c-select

(It also is worth thinking through how this would interact with [`Stripe.max_network_retries`](https://github.com/stripe/stripe-ruby#configuring-automatic-retries), which I think we currently have set to `0`)

**Comment by dunkOnIT** [comment]
Closed because the function being referenced doesn't exist in our code anymore. @gregorbg pinging for visibility

**Comment by gregorbg** [comment]
Yup, happy to confirm that the way we interact with Stripe has fundamentally changed since this issue was originally written, so entirely not relevant anymore
