### ISSUE TITLE
Certain combinations of filter criteria break the rankings page

### ISSUE THREAD

**Issue by gregorbg** [thewca/worldcubeassociation.org#6325]
**Describe the bug**
When combining particular filter critera, the ranking page yields the "We're sorry, but something went wrong" error page

**To Reproduce**
Steps to reproduce the behavior [EXAMPLE, breaks for several other conditions as well]:
1. Go to "Rankings"
2. Choose the Megaminx event
3. Filter for Female competitors
4. Filter for Averages
5. Filter "By region"
6. Filter for years until 2006
7. KABOOM

**Expected behavior**
An empty rankings page is being displayed

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux 5.10.42
 - Browser: Chrome
 - Version: 91.0.4472.77

**Smartphone (please complete the following information):**
 N/A

**Additional context**
Presumably the SQL query yields a non-trivial result set. According to the staging logs, there is a `Nil` result involved somewhere.

```
I, [2021-06-25T22:43:37.961849 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304] Started GET "/results/rankings/minx/average?gender=Female&show=by+region&years=until+2006" for 79.207.189.56 at 2021-06-25 22:43:37 +0000
I, [2021-06-25T22:43:37.963404 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304] Processing by ResultsController#rankings as HTML
I, [2021-06-25T22:43:37.963461 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Parameters: {"gender"=>"Female", "show"=>"by region", "years"=>"until 2006", "event_id"=>"minx", "type"=>"average"}
D, [2021-06-25T22:43:37.972269 #8434] DEBUG -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]    (6.5ms)  SELECT `Competitions`.`year` FROM `Competitions` WHERE `Competitions`.`showAtAll` = TRUE
I, [2021-06-25T22:43:37.982184 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Rendering results/rankings.html.erb within layouts/application
D, [2021-06-25T22:43:37.984508 #8434] DEBUG -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Event Load (1.3ms)  SELECT `Events`.* FROM `Events` WHERE (`rank` < 990) ORDER BY `Events`.`rank` ASC
I, [2021-06-25T22:43:38.010826 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Rendered results/_results_selector.html.erb (28.2ms)
D, [2021-06-25T22:43:38.012743 #8434] DEBUG -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Timestamp Load (1.2ms)  SELECT  `timestamps`.* FROM `timestamps` WHERE `timestamps`.`name` = 'compute_auxiliary_data_end' LIMIT 1
D, [2021-06-25T22:43:38.418850 #8434] DEBUG -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   SQL (405.4ms)          SELECT
          result.*,
          result.average value
        FROM (
          SELECT
            result.countryId recordCountryId,
            MIN(average) recordValue
          FROM ConciseAverageResults result
          JOIN Persons persons ON result.personId = persons.id and persons.subId = 1
          WHERE 1
            AND eventId = 'minx'
            AND result.year <= 2006
            AND gender = 'f'
          GROUP BY result.countryId
        ) record
        JOIN Results result ON result.average = recordValue AND result.countryId = recordCountryId
        JOIN Competitions competition on competition.id = competitionId
        JOIN Persons persons ON result.personId = persons.id and persons.subId = 1
        WHERE 1
          AND eventId = 'minx'
          AND competition.year <= 2006
          AND gender = 'f'
        ORDER BY value, countryId, start_date, personName

D, [2021-06-25T22:43:38.420830 #8434] DEBUG -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Competition Load (1.3ms)  SELECT `Competitions`.* FROM `Competitions` WHERE 1=0
I, [2021-06-25T22:43:38.422201 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Rendered results/_rankings_by_region_table.html.erb (1.1ms)
I, [2021-06-25T22:43:38.422367 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]   Rendered results/rankings.html.erb within layouts/application (440.1ms)
I, [2021-06-25T22:43:38.422611 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304] Completed 500 Internal Server Error in 459ms (ActiveRecord: 415.6ms)
I, [2021-06-25T22:43:38.422883 #8434]  INFO -- : [a7117224-b0b1-4c27-8d1c-629a581e2304] [User Id] Request was made by user id: <not logged in>
F, [2021-06-25T22:43:38.424251 #8434] FATAL -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]
F, [2021-06-25T22:43:38.424293 #8434] FATAL -- : [a7117224-b0b1-4c27-8d1c-629a581e2304] ActionView::Template::Error (undefined method `[]' for nil:NilClass):
F, [2021-06-25T22:43:38.424467 #8434] FATAL -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]     1: <% rows_to_display, first_continent_index, first_country_index = compute_rankings_by_region(@rows, @continent, @country) %>
[a7117224-b0b1-4c27-8d1c-629a581e2304]     2: <%= wca_table table_class: "wca-results" do %>
[a7117224-b0b1-4c27-8d1c-629a581e2304]     3:   <thead>
[a7117224-b0b1-4c27-8d1c-629a581e2304]     4:     <tr>
F, [2021-06-25T22:43:38.424497 #8434] FATAL -- : [a7117224-b0b1-4c27-8d1c-629a581e2304]
F, [2021-06-25T22:43:38.424518 #8434] FATAL -- : [a7117224-b0b1-4c27-8d1c-629a581e2304] app/helpers/results_helper.rb:33:in `compute_rankings_by_region'
[a7117224-b0b1-4c27-8d1c-629a581e2304] app/views/results/_rankings_by_region_table.html.erb:1:in `_app_views_results__rankings_by_region_table_html_erb__4034573802227995242_105792100'
[a7117224-b0b1-4c27-8d1c-629a581e2304] app/views/results/rankings.html.erb:22:in `block in _app_views_results_rankings_html_erb___2926773708043788757_70101186865260'
[a7117224-b0b1-4c27-8d1c-629a581e2304] app/views/results/rankings.html.erb:11:in `_app_views_results_rankings_html_erb___2926773708043788757_70101186865260'
[a7117224-b0b1-4c27-8d1c-629a581e2304] lib/middlewares/warden_user_logger.rb:13:in `call'
[a7117224-b0b1-4c27-8d1c-629a581e2304] lib/middlewares/fix_accept_header.rb:14:in `call'
```

**Comment by louismeunier** [comment]
Taking a quick look, this seems to be due to the `compute_rankings_by_region` function to not check if the `rows` parameter is not `nil` before indexing it. Seems like an easy enough fix, which I can work on, if I may!

**Comment by gregorbg** [comment]
By all means, go ahead!

Some breadcrumbs: The method is in `WcaOnRails/app/helpers/results_helper.rb`. The rows are computed in `WcaOnRails/app/views/results/rankings.html.erb`.
I am fairly confident that the SQL query does not return `nil`, even when the result set is empty it should just be an empty list. So the problem has to lie somewhere else.
