### ISSUE TITLE
Error sorting competitions by announcement date

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#7723]
When I [sort by announcement date](https://www.worldcubeassociation.org/competitions?region=all&search=&year=all+years&state=by_announcement&from_date=&to_date=&delegate=&display=list) I get an error:
```
We're sorry, but something went wrong.
If you report this error to the Software Team please mention the Request ID

Request ID: 5cd3bacc-22f5-4b80-a721-ef8dd32b55ab
```

**Comment by FinnIckler** [comment]
here is the stack trace

```
2023-03-07T15:37:13.528170 #2668666]  INFO -- : [5cd3bacc-22f5-4b80-a721-ef8dd32b55ab] Completed 500 Internal Server Error in 235ms (ActiveRecord: 30.4ms | Allocations: 173713)
F, [2023-03-07T15:37:13.529198 #2668666] FATAL -- : [5cd3bacc-22f5-4b80-a721-ef8dd32b55ab]
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab] ActionView::Template::Error (undefined method `strftime' for nil:NilClass):
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab]     18:         <% elsif competition.in_progress? %>
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab]     19:           <%= ui_icon('hourglass half', title: t('competitions.index.tooltips.hourglass.in_progress'), data: { toggle: "tooltip" }) %>
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab]     20:         <% elsif @by_announcement_selected %>
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab]     21:           <%= ui_icon('hourglass start', title: t('competitions.index.tooltips.hourglass.announced_on', announcement_date: competition.announced_at.strftime(" %F %H:%M:%S")), data: { toggle: "tooltip" }) %>
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab]     22:         <% elsif @show_registration_status %>
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab]     23:           <%= registration_status_icon(competition) %>
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab]     24:         <% else %>
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab]
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab] app/views/competitions/_index_table.html.erb:21
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab] app/views/competitions/_index_table.html.erb:3:in `each_with_index'
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab] app/views/competitions/_index_table.html.erb:3
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab] app/views/competitions/_index_competitions_list.html.erb:18
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab] app/views/competitions/index.html.erb:17
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab] lib/middlewares/warden_user_logger.rb:13:in `call'
[5cd3bacc-22f5-4b80-a721-ef8dd32b55ab] lib/middlewares/fix_accept_header.rb:14:in `call'
```

**Comment by gregorbg** [comment]
This is not a general problem in our code. It is only specifically happening now because one competition is in a weird state where it's set to "publicly visible" while not being announced. I have reached out to WCAT and the Delegates to figure this out ASAP.

**Comment by gregorbg** [comment]
Fixed manually by WCAT.
