### ISSUE TITLE
Errors when using docker compose up on a fresh repository

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#9093]
**Describe the bug**

When trying to `docker compose up` the website in a brand new cloned repository, with past containers/volumes cleaned up, I encountered several errors.

First of all, sidekiq failed to load: after the `rails` container seemed to be populated and running, I saw this in the log

```
sidekiq      | bundler: failed to load command: sidekiq (/usr/local/bundle/bin/sidekiq)
sidekiq      | /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- ffi (LoadError)
sidekiq      | 	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
```
(the rest of the trace has been removed since it just goes back to the original bundler command)

It didn't seem to be preventing the server from starting up, and I could load the home page.
However when signing in I got the following error:

```
rails        | [User Id] Request was made by user id: <not logged in>
rails        | Processing by SessionsController#new as HTML
rails        |   Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"login"=>"2008VIRO01", "password"=>"[FILTERED]", "remember_me"=>"1"}, "commit"=>"Sign in"}
rails        | Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms | Allocations: 2010)
rails        | 
rails        | 
rails        |   
rails        | LoadError (libruby.so.3.2: cannot open shared object file: No such file or directory - /usr/local/bundle/gems/bcrypt-3.1.19/lib/bcrypt_ext.so):
rails        |   
```

This one seems very strange since it expects a ruby version that doesn't exist in the Dockerfile.

The only difference I can notice with the CI is that the image in the CI is based on ubuntu:latest and then install ruby 3.3.0 from precompiled binaries; whereas docker's `ruby:3.3.0` is based on debian bookworm.
Do you guys still use the docker compose system or have you started using something else?

I'll try basing the dockerfiles on ubuntu:latest and then install ruby 3.3.0 (to mimic what the CI does), but in the meantime if you have any suggestions please let me know :)

**To Reproduce**
  - stop/destroy all containers/volumes
  - clone a fresh website repository
  - docker compose up
  - sign in

**Expected behavior**

It starts up without errors and I can use the website normally :p

**Desktop (please complete the following information):**
 - OS: debian 12
 - Browser: N/A

**Comment by viroulep** [comment]
Following up some discussions with @gregorbg: what I did to cleanup my past docker images/containers is the following:
  - I `docker image rm`-ed all the worldcubeassociation images
  - I `docker compose down` + `docker compose down --volumes` the things
  - I `docker system prune`-ed
And then removed the whole repository folder + cloned it again, then ran `docker compose up`.

Gregor pointed out to me that he would periodically use `docker-compose --build` (which translates to `docker compose build` if I'm not mistaken); I cleaned up the docker images and ran this, and then ran `docker compose up`.

I ran into a silly compilation issue because I forgot to remove the `.db-inited` file, but at the end of this process I did get a working environment, with the issue in #9094 gone too!

I'm not too sure what happened there, but I can only assume there was still somewhere on my system a docker layer which has been picked up by docker compose when it should have created it from scratch; I can't really explain how this could happen after removing + pruning the images though!

I think we can close this and encourage/point people to `docker compose build` first!
