### ISSUE TITLE
Improve handling of STMP 501 Invalid RCPT TO address provided during signup

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#934]
See email [here](https://groups.google.com/d/msg/wca-admin/kXCH6Nrq6-g/rrhEn1c3CgAJ).

In short, we are seeing job failures related to people signing up for accounts with invalid email addresses:

`#<Net::SMTPSyntaxError: 501 Invalid RCPT TO address provided >`

We did not run into this in the past because we sent email synchronously (rather than in a background job). I'm going to experiment with disabling [this code](https://github.com/thewca/worldcubeassociation.org/blob/73da1e062b842741f1fd7c6a9ea597fb8f7feedc/WcaOnRails/app/models/user.rb#L313-L316), and see what the user experience is like when entering an email that amazon SES dislikes.

**Comment by jfly** [comment]
As expected, attempting to send an email synchronously gives us a 500 HTTP code. Pretty scary, but at least it's clear that something didn't work:

# Filling out sign up form

![image](https://cloud.githubusercontent.com/assets/277474/19285536/2c8cd360-8faf-11e6-94ea-9314a8a1c7c9.png)

# After clicking "Sign up"

![image](https://cloud.githubusercontent.com/assets/277474/19285603/74356970-8faf-11e6-8b7d-3f9c6fcfcaeb.png)

# Logs

```ruby
I, [2016-10-11T19:33:09.572047 #14899]  INFO -- :
Sent mail to =?UTF-8?B?c8OtQGV4YW1wbGUub3Jn?= (209.6ms)
D, [2016-10-11T19:33:09.572121 #14899] DEBUG -- : Date: Tue, 11 Oct 2016 19:33:09 +0000
From: notifications@worldcubeassociation.org
Reply-To: notifications@worldcubeassociation.org
To: =?UTF-8?B?c8OtQGV4YW1wbGUub3Jn?=
Message-ID: <57fd3e7559ab3_3a33c350dc326c5@production.mail>
Subject: Confirmation instructions
Mime-Version: 1.0  
Content-Type: multipart/alternative;
 boundary="--==_mimepart_57fd3e75586e3_3a33c350dc325c";
 charset=UTF-8
Content-Transfer-Encoding: 7bit


----==_mimepart_57fd3e75586e3_3a33c350dc325c
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Welcome s=C3=AD@example.org!

You can confirm your account email through the link below:

Confirm my account ( https://www.worldcubeassociation.org/users/confirmat=
ion?confirmation_token=3DMxJVReXy5d5fkJnPkmyx&locale=3Den )=

----==_mimepart_57fd3e75586e3_3a33c350dc325c
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www=
.w3.org/TR/REC-html40/loose.dtd">
<html><body>
<p>Welcome s=C3=AD@example.org!</p>

<p>You can confirm your account email through the link below:</p>

<p><a href=3D"https://www.worldcubeassociation.org/users/confirmation?con=
firmation_token=3DMxJVReXy5d5fkJnPkmyx&amp;locale=3Den">Confirm my accoun=
t</a></p>
</body></html>

----==_mimepart_57fd3e75586e3_3a33c350dc325c--

D, [2016-10-11T19:33:09.575963 #14899] DEBUG -- :    (3.7ms)  ROLLBACK
I, [2016-10-11T19:33:09.576660 #14899]  INFO -- : Completed 500 Internal Server Error in 3085ms (ActiveRecord: 261.4ms)
I, [2016-10-11T19:33:09.576947 #14899]  INFO -- : [User Id] Request was made by user id: <not logged in>
F, [2016-10-11T19:33:09.578631 #14899] FATAL -- :
Net::SMTPSyntaxError (501 Invalid RCPT TO address provided
):
  lib/middlewares/warden_user_logger.rb:12:in `call'
  lib/middlewares/fix_accept_header.rb:13:in `call'


```

**Comment by jfly** [comment]
I'm fine with closing this issue. If we ever start getting tons of signups and this becomes an issue, we can always revisit it.
